/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ncnbasvptocuwgxvyjmw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jbmJhc3ZwdG9jdXdneHZ5am13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1NTA1MjEsImV4cCI6MjA4NDEyNjUyMX0.766CPDI3GU-Rt4g5IRdRS-HPR84cCtlV7Ub-vHX0N4Q"